#!/bin/sh

# For Red Hat chkconfig
# chkconfig: - 80 30
# description: the qmail MTA
# Modified by kamran to manage smtpd-tls as well

PATH=/var/qmail/bin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin
export PATH

QMAILDUID=`id -u qmaild`
NOFILESGID=`id -g qmaild`

case "$1" in
  start)
    echo "Starting qmail"
    if svok /service/qmail-send ; then
      svc -u /service/qmail-send /service/qmail-send/log
    else
      echo "qmail-send supervise not running"
    fi

    if svok /service/qmail-smtpd ; then
      svc -u /service/qmail-smtpd /service/qmail-smtpd/log
    else
      echo "qmail-smtpd supervise not running"
    fi

    if svok /service/qmail-smtpd-tls ; then
      svc -u /service/qmail-smtpd-tls /service/qmail-smtpd-tls/log
    else
      echo "qmail-smtpd-tls supervise not running"
    fi


    if [ -d /var/lock/subsys ]; then
      touch /var/lock/subsys/qmail
    fi
    ;;
  stop)
    echo "Stopping qmail..."

    echo "  qmail-smtpd-tls"
    svc -d /service/qmail-smtpd-tls /service/qmail-smtpd-tls/log

    echo "  qmail-smtpd"
    svc -d /service/qmail-smtpd  /service/qmail-smtpd/log

    echo "  qmail-send"
    svc -d /service/qmail-send /service/qmail-send/log

    if [ -f /var/lock/subsys/qmail ]; then
      rm /var/lock/subsys/qmail
    fi
    ;;
  stat|status)
    svstat /service/qmail-send
    svstat /service/qmail-send/log
    svstat /service/qmail-smtpd
    svstat /service/qmail-smtpd/log
    svstat /service/qmail-smtpd-tls
    svstat /service/qmail-smtpd-tls/log
    qmail-qstat
    ;;
  doqueue|alrm|flush)
    echo "Flushing timeout table and sending ALRM signal to qmail-send."
    /var/qmail/bin/qmail-tcpok
    svc -a /service/qmail-send
    ;;
  queue)
    qmail-qstat
    qmail-qread
    ;;
  reload|hup)
    echo "Sending HUP signal to qmail-send."
    svc -h /service/qmail-send
    ;;
  pause)
    echo "Pausing qmail-send"
    svc -p /service/qmail-send

    echo "Pausing qmail-smtpd"
    svc -p /service/qmail-smtpd

    echo "Pausing qmail-smtpd-tls"
    svc -p /service/qmail-smtpd-tls
    ;;
  cont)
    echo "Continuing qmail-send"
    svc -c /service/qmail-send

    echo "Continuing qmail-smtpd"
    svc -c /service/qmail-smtpd
    echo "Continuing qmail-smtpd-tls"
    svc -c /service/qmail-smtpd-tls
    ;;
  restart)
    echo "Shutting Down qmail:"
    echo "* Stopping qmail-smtpd and qmail-smtpd-tls."
    svc -d /service/qmail-smtpd /service/qmail-smtpd/log
    svc -d /service/qmail-smtpd-tls /service/qmail-smtpd-tls/log

    echo "* Sending qmail-send SIGTERM and restarting."
    svc -t /service/qmail-send /service/qmail-send/log

    echo "* Starting Up qmail-smtpd."
    svc -u /service/qmail-smtpd /service/qmail-smtpd/log
    svc -u /service/qmail-smtpd-tls /service/qmail-smtpd-tls/log
    ;;
  cdb)
    # Kamran: 20151130 . Added a better way to make all CDB files instead of just one.
    # tcprules /etc/tcp.smtp.cdb /etc/tcp.smtp.tmp < /etc/tcp.smtp
    # chmod 644 /etc/tcp.smtp.cdb
    echo "Rebuilding CDB files in  /etc/tcp/ "
    pushd /etc/tcp
    make
    popd
    ;;
  help)
    cat <<HELP
   stop -- stops mail service (smtp connections refused, nothing goes out)
  start -- starts mail service (smtp connection accepted, mail can go out)
  pause -- temporarily stops mail service (connections accepted, nothing leaves)
   cont -- continues paused mail service
   stat -- displays status of mail service
 status -- same as stat
    cdb -- rebuild the tcpserver cdb file for smtp
restart -- stops and restarts smtp, sends qmail-send a TERM & restarts it
doqueue -- schedules queued messages for immediate delivery
 reload -- sends qmail-send HUP, rereading locals and virtualdomains
  queue -- shows status of queue
   alrm -- same as doqueue
  flush -- same as doqueue
    hup -- same as reload
HELP
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|doqueue|flush|reload|stat|status|pause|cont|cdb|queue|help}"
    exit 1
    ;;
esac

exit 0

